notifications:
  email:
    on_success: [change] # default: change
    on_failure: [change] # default: always

sudo: required

language: php

php:
  - 7.0

services:
  - docker

addons:
  hosts:
    - mellivora

before_script:
# Environment setup
  - bash tests/ci/setup_environment
  - docker-compose -f docker-compose.dev.yml up -d

script:
  - bash tests/run_tests --debug