version: '3'
services:
  mellivora:
    environment:
      MELLIVORA_CONFIG_SITE_URL: http://mellivora/
      MELLIVORA_CONFIG_SITE_URL_STATIC_RESOURCES: http://mellivora/
  codecept:
    image: eccube/php7-ext-codeception
    depends_on:
      - chrome
      - mellivora
      - db
    volumes:
      - .:/project
  chrome:
    image: 'selenium/standalone-chrome-debug'
    ports:
        - '5900'
        - '4444'
    dns: 8.8.4.4
    environment:
      - no_proxy=localhost